version: "3.9"

services:

  api:
    build:
      context: .
    ports:
      - 5000:5000
    depends_on:
      pg:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
  migrations:
    build:
      context: .
    depends_on:
      pg:
        condition: service_healthy
    command: bash -c "flask db upgrade && python load_fixtures.py"
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: flask_app_user
      POSTGRES_PASSWORD: flask_app_password
      POSTGRES_DB: flask_app_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
